version: '3.7'

services:

#  x-mentor-core:
#    image: xmentor/x-mentor-core:latest
#    restart: always
#    environment:
#        - "REDIS_HOST=x-redis"
#        - "CLIENT_BASE_AUTH_URL=http://x-keycloak:8080/auth"
#    ports:
#      - 9000:9000
#    entrypoint: ["/opt/docker/conf/wait-for-keycloak.sh", "/opt/docker/conf/wrapper.sh"]
#    depends_on:
#      - x-redis
#      - x-keycloak
      
#  x-mentor-client:
#    image: xmentor/x-mentor-client:latest
#    ports:
#      - 3000:80
#    depends_on:
#      - x-mentor-core

#  x-redis:
#    image: redislabs/redismod:feature-search-json
#    restart: always
#    ports:
#      - 6379:6379
      
  x-keycloak:
    image: jboss/keycloak
    restart: always
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/tmp/realm-export.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    environment:
      - KEYCLOAK_USER:admin
      - KEYCLOAK_PASSWORD:admin
    ports:
      - 8880:8080
      
  x-neo4j:
    image: neo4j
    restart: always
    volumes:
      - ./neo4j/data:/data
    environment:
      #For prod
      #- NEO4J_AUTH=admin/admin
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
      
  x-postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgres/data:/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=xmentor
    ports:
      - 5432:5432

  x-rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 8081:15672
      - 5672:5672
      -
  x-sonarqube:
    image: sonarqube
    restart: always
    ports:
      - 9090:9000
      - 9092:9092